#!/bin/bash

echo "🚀 Render Deployment Helper for Clicko Flow"
echo "============================================"
echo ""

echo "📋 **Deployment Steps:**"
echo "1. Go to: https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New +' → 'Blueprint'"
echo "4. Connect your Clicko Flow repository"
echo "5. Render will auto-detect render.yaml"
echo "6. Click 'Apply' to deploy both services"
echo ""

echo "🔧 **Required Environment Variables:**"
echo ""
echo "Backend API Service (clicko-flow-api):"
echo "- MONGODB_URI: Your MongoDB Atlas connection string"
echo "- JWT_SECRET: A secure random string for JWT tokens"
echo "- CORS_ORIGIN: https://clicko-flow-frontend.onrender.com"
echo ""
echo "Frontend Service (clicko-flow-frontend):"
echo "- REACT_APP_API_URL: https://clicko-flow-api.onrender.com/api"
echo "- REACT_APP_ENVIRONMENT: production"
echo ""

echo "🌐 **Service URLs After Deployment:**"
echo "- Backend API: https://clicko-flow-api.onrender.com"
echo "- Frontend: https://clicko-flow-frontend.onrender.com"
echo "- Health Check: https://clicko-flow-api.onrender.com/api/health"
echo ""

echo "💡 **Why Render is Great:**"
echo "- Free tier: 750 hours/month"
echo "- Auto-sleep/wake for cost optimization"
echo "- Global CDN for fast loading"
echo "- SSL certificates included"
echo "- One-click blueprint deployment"
echo ""

echo "📚 **Full Guide:** See RENDER_DEPLOYMENT.md for detailed instructions"
echo ""

echo "🎯 **Ready to deploy?**"
echo "Visit: https://render.com"
echo "Choose: New + → Blueprint"
echo "Connect: Your GitHub repository"
echo "Deploy: Click Apply!"
