services:
  # Backend API Service
  - type: web
    name: clicko-flow-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false

  # Frontend React App
  - type: static
    name: clicko-flow-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://clicko-flow-api.onrender.com/api
      - key: REACT_APP_ENVIRONMENT
        value: production
