services:
  - type: web
    name: clicko-flow-dashboard
    env: node
    plan: free
    buildCommand: npm run build-all
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
